[webservers]
# Remplace l'IP par celle de ton VPS Hostinger.
# Pour déployer sur plusieurs serveurs en parallèle, ajoute d'autres lignes (server2, server3...).
server1 ansible_host=46.202.171.191



# configurations stocké dans vars pour tous les servers cibles de la liste
# il dit ou aller chercher le programme python sur chqaue server
[webservers:vars]
ansible_python_interpreter=/usr/bin/python3
