[webservers]
# Remplace l'IP par celle de ton VPS Hostinger.
# Pour déployer sur plusieurs serveurs en parallèle, ajoute d'autres lignes (server2, server3...).
server1 ansible_host=REMPLACE_PAR_IP_DU_VPS

[webservers:vars]
ansible_python_interpreter=/usr/bin/python3
