---
# Fichier principal d'orchestration pour le projet
- name: Deploy WordPress stack
  # la cible ( list defini dans inventory.ini )
  hosts: webservers
  # execute les opération en root sur les servers
  become: true # Requis pour installer des paquets et modifier le pare-feu
  

  # va chercher dans le dossier roles puis task et executer le main de chaque
  # sous dossier role/task
  roles:
    # 1. Prépare la machine en installant le moteur Docker
    - docker
    
    # 2. Sécurise le serveur en fermant les ports inutiles (seuls accessible :  22, 80, 443)
    - ufw
    
    # 3. Copie les fichiers de configuration et lance les conteneurs (WordPress, DB, Nginx)
    - app