---

# ==============================================================================
# RÔLE WORDPRESS

# pour les languages interpreted (diff de compiled qui lit une fois et 
# traduit)

# interet run time (pas gestion memoire, portable)
# pas memoire => interpreteur fait la gestion car il a les ressources
# en live

# en compile on sait pas a l avance donc on doit tout gerer

# run time = programme qui lit ton code et execute (l interpreteur)
# js = node js
# python = python3


# run time php = php fpm

# ==============================================================================


# Bloc 1 : copie le compose de WordPress dans le dossier de travail
- name: Deploy the WordPress compose file
  template:
    src: compose.wordpress.yml.j2
    dest: "{{ project_dir }}/compose.wordpress.yml"
    mode: '0644'


# Bloc 2 : lance ou maj le docker wordpress
- name: Start WordPress (php-fpm)
  command: >-
    docker compose -f docker-compose.yml -f compose.db.yml
    -f compose.wordpress.yml up -d wordpress
  args:
    chdir: "{{ project_dir }}"
  register: wp_up
  # Idem que pour la base : "changed" seulement si Docker a vraiment bougé.
  changed_when: >
    ('Started' in wp_up.stderr) or ('Created' in wp_up.stderr)
    or ('Recreated' in wp_up.stderr)


# Bloc 3 : attendre que l'image WordPress ait fini de copier ses files
# Car l image met du temps a copier mais compose passe a la suite
# sans attendre, donc sans pause sa buggerais (pas de fichier sur leqauel travailler)
- name: Wait for WordPress files to be extracted

  # verifie si le fichier dont on a besoin  est la (version php)
  command: >-
    docker compose -f docker-compose.yml -f compose.db.yml
    -f compose.wordpress.yml exec -T wordpress
    sh -c "test -f /var/www/html/wp-includes/version.php"
  args:
    chdir: "{{ project_dir }}"
  register: wp_files
  until: wp_files.rc == 0 
  retries: 30
  delay: 5
  changed_when: false
  failed_when: false


- name: Fail with a clear message if WordPress files never appeared
  fail:
    msg: "WordPress n'a pas fini de s'extraire. Verifier : docker compose logs wordpress"
  when: wp_files.rc != 0







# ==============================================================================
# INSTALLATION AUTOMATIQUE DE WORDPRESS (wp-cli)

# install avec le cli

# ==============================================================================


# Bloc 4 : WordPress est-il deja installe ?
# 'core is-installed' renvoie 0 si oui, 1 sinon.

- name: Check whether WordPress is already installed

  #  profil est coller sur un service pour qu il ne start pas avec 
  # le reste

  # --profile check que via le profil docker (separe du compose up general)
  #
  # run = cree un container neuf (exec userai u ndeja existant)
  # --rm  supprime des que la cmd a ete test dedans 
  # -T = pas de terminal interactif
  # wpcli = nom du service 
  #
  # wp = le programme
  # core = categorie de cmd
  #   demande si is isntalled

  # docker check 3 fichier yaml (le general, db et wp)
  #  prend les 3 fichier active le profil et cree un nouveau
  # ainsi il est sur le meme reseau que la db, il voit les fichier de wp
  # les id de la db avec le .env
  command: >-
    docker compose -f docker-compose.yml -f compose.db.yml
    -f compose.wordpress.yml --profile tools run --rm -T wpcli wp core is-installed
  args:
    chdir: "{{ project_dir }}"
  register: wp_is_installed
  changed_when: false
  failed_when: false


# Bloc 5 : installation (titre, compte admin) - seulement si necessaire

# container temporaire aussi mais pour config le compte url etc dans les volume et db
- name: Install WordPress
  command: >-
    docker compose -f docker-compose.yml -f compose.db.yml
    -f compose.wordpress.yml --profile tools run --rm -T wpcli wp core install
    --url={{ wp_site_url }}
    --title={{ wp_site_title }}
    --admin_user={{ wp_admin_user }}
    --admin_password={{ wp_admin_password }}
    --admin_email={{ wp_admin_email }}
    --skip-email
  args:
    chdir: "{{ project_dir }}"
  when: wp_is_installed.rc != 0 # Se declahnce que si pas deja cree
  register: wp_install
  changed_when: wp_install.rc == 0
  # Rien n'est affiche quand la tache reussit ;