---
# est appelé si changement dans certaines config

- name: Recreate stack
  # --force-recreate car les variables d'env sont figées au lancement du
  # conteneur : un simple up -d ne relirait pas le nouveau .env.
  # --remove-orphans suppr les anciens docker zombie
  command: docker compose up -d --force-recreate --remove-orphans
  args:
  # se met dans l'endroit ou il y a le docker compose pour pouvoir le lancer
    chdir: "{{ project_dir }}"
